import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { FiMenu } from 'react-icons/fi'
import { useState } from 'react'

export default function Home() {
  const [clicked, setClicked] = useState(false)
  const handleClick = () => {
    if (clicked === false) {
      setClicked(true)
    }
    else {
      setClicked(false)
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-1 justify-between p-3 bg-orange-300">
        <div className="text-2xl font-semibold">Lorem</div>
        <div className="hidden sm:flex">decrese the width of window</div>
        <div className=" my-auto cursor-pointer mr-3 flex sm:hidden" onClick={handleClick}><FiMenu size={26} /></div>
      </div>

      {clicked &&
        <div className="flex bg-purple-300 fade-in max-w-fit p-2 rounded-lg ml-auto mr-2 -mt-2 flex-col">
          <div className="hover:bg-white p-2 rounded-lg cursor-pointer">Lorem, ipsum.</div>
          <div className="hover:bg-white p-2 rounded-lg cursor-pointer">Lorem, ipsum.</div>
          <div className="hover:bg-white p-2 rounded-lg cursor-pointer">Lorem, ipsum.</div>
          <div className="hover:bg-white p-2 rounded-lg cursor-pointer">Lorem, ipsum.</div>
          <div className="hover:bg-white p-2 rounded-lg cursor-pointer">Lorem, ipsum.</div>
        </div>}
    </>
  )
}
